package org.hxy.platform.android.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.hxy.platform.android.common.entity.GoodsOrderInfoBean;

import org.hxy.platform.android.common.greendao.GoodsOrderInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsOrderInfoBeanDaoConfig;

    private final GoodsOrderInfoBeanDao goodsOrderInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsOrderInfoBeanDaoConfig = daoConfigMap.get(GoodsOrderInfoBeanDao.class).clone();
        goodsOrderInfoBeanDaoConfig.initIdentityScope(type);

        goodsOrderInfoBeanDao = new GoodsOrderInfoBeanDao(goodsOrderInfoBeanDaoConfig, this);

        registerDao(GoodsOrderInfoBean.class, goodsOrderInfoBeanDao);
    }
    
    public void clear() {
        goodsOrderInfoBeanDaoConfig.clearIdentityScope();
    }

    public GoodsOrderInfoBeanDao getGoodsOrderInfoBeanDao() {
        return goodsOrderInfoBeanDao;
    }

}
